packages:
  - webapp
  - ingest
  - functions

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@firebase/util'
  - bootstrap-vue
  - core-js
  - esbuild
  - protobufjs
  - vue-demi

catalog:
  '@biomejs/biome': ^1.9.4
