import { recipeDocId, slugify } from "../src/recipe-id.js";

// These expectations encode the behaviour of ingest/json-gen.ts, quirks included.
// The existing ~50 document IDs were generated by that script, so "fixing" any
// of the oddities below would orphan documents rather than rename them.
describe("slugify", () => {
	it("turns a forward slash into an underscore (via an intermediate backslash)", () => {
		// "/" becomes "\", which is itself non-word and so collapses to "_".
		expect(slugify("Ris/Quinoa")).toBe("Ris_Quinoa");
	});

	it("transliterates Swedish characters", () => {
		expect(slugify("Kanelbullar med äpple och örter")).toBe(
			"Kanelbullar_med_aepple_och_oerter",
		);
	});

	it("collapses runs of non-word characters into a single underscore", () => {
		expect(slugify("Pasta   med  -- tomat!")).toBe("Pasta_med_tomat_");
	});

	it("lowercases uppercase Swedish characters when transliterating", () => {
		// The /gi flag matches "Ä" but substitutes the lowercase "ae".
		expect(slugify("Ägg Åre Öl")).toBe("aegg_aare_oel");
	});
});

describe("recipeDocId", () => {
	it("joins category segments with backslashes before the title", () => {
		expect(recipeDocId(["Huvudrätter", "Pasta"], "Lasagne")).toBe(
			"Huvudrätter\\Pasta\\Lasagne",
		);
	});

	it("keeps Swedish letters in categories but transliterates them in titles", () => {
		expect(recipeDocId(["Bakverk & Bröd"], "Äppelpaj")).toBe(
			"Bakverk_Bröd\\aeppelpaj",
		);
	});

	it("handles a single-segment category", () => {
		expect(recipeDocId(["Soppor"], "Linssoppa")).toBe("Soppor\\Linssoppa");
	});
});
